language: node_js
node_js: stable
sudo: required
dist: xenial

branches:
  only:
    - source  

install:
  - mkdir work
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
    -O $PWD/work/hugo.deb
  - sudo dpkg -i $PWD/work/hugo.deb
  - npm install  

script:
  - hugo -v

after_script:
  - git config --global user.name ${GIT_USER}
  - git config --global user.email ${GIT_EMAIL}
  - git clone https://${GH_TOKEN}@${REPO} container
  - rm -rf container/*
  - cp -r public/* container 
  - cd container
  - echo "han1475.com" >> CNAME
  - echo "Personal site of han1475, managed by emacs, org mode, git, ox-hugo, and travis." >> README.md
  - git add .
  - git commit -m 'Travis upate blog'
  - git push -u origin master -f

env:
  global:
    - REPO="github.com/han1475/han1475.github.io.git"
    - GIT_USER="han1475"
    - GIT_EMAIL="me@han1475.com"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="master"

