baseURL = "https://han1475.com/"
languageCode = "en-us"
title = "小蜗牛的大梦想"
theme = "cupcake"

# Highlight options.
# @See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

[params]
  # The date format to use; for a list of valid formats
  # @see https://gohugo.io/functions/format/
  dateFormatToUse = "2006年1月2号"

  # site motto
  motto = '多说无益，放"码"过来'

[params.social]
    a-email = "mailto:me@han1475.com"
    g-github = "https://github.com/han1475"