name: build and publish 

on:
  push:
    branches: 
      - source
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: build and push
      run: |
        git config --global user.name ${GIT_USER}
        git config --global user.email ${GIT_EMAIL}
        
        echo 'Downloading hugo'
        mkdir work
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb -O $PWD/work/hugo.deb
        sudo dpkg -i $PWD/work/hugo.deb
        
        echo 'Building the hugo site'
        git clone -b source --recursive https://${GH_TOKEN}@${REPO} source
        cd source
        hugo -v 
        
        echo 'Cloning the GitHub Pages repo'
        rm -rf "${BUILD_DIR}"
        git clone -b master https://${GH_TOKEN}@${REPO} "${BUILD_DIR}"

        
        echo 'Moving the content over'
        rm -rf "${BUILD_DIR}/*"
        cp -r public/* "${BUILD_DIR}"
        cd "${BUILD_DIR}"
        if git diff --exit-code; then
          echo "There is nothing to commit, so aborting"
        else
          echo 'Committing the site to git and pushing'
          git add .
          git commit -m 'upate blog'
          git push origin -f
        fi
      env:
        GIT_USER: han1475
        GIT_EMAIL: me@han1475.com
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPO: github.com/han1475/han1475.github.io.git
        BUILD_DIR: container
        HUGO_VERSION: 0.78.2
